import {Dimensions, StyleSheet} from 'react-native';
import {color} from 'react-native-elements/dist/helpers';
import {TableWrapper} from 'react-native-table-component';
const {width, height} = Dimensions.get('window');

export const styles = StyleSheet.create({
  chatscreen: {
    backgroundColor: '#FFF9F0',
    flex: 1,
    padding: 10,
    position: 'relative',
  },
  chatheading: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#E24E59',
  },
  chattopContainer: {
    // backgroundColor: '#F7F7F7',
    height: 80,
    width: '100%',
    padding: 20,
    justifyContent: 'center',
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(112,112,112,0.5)',
    // elevation: 2,
  },
  chatheader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  chatlistContainer: {
    paddingHorizontal: 10,
  },
  chatemptyContainer: {
    marginTop: 20,
    width: '100%',
    height: '80%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatemptyText: {fontWeight: 'bold', fontSize: 24, paddingBottom: 30},
  messagingscreen: {
    flex: 1,
    backgroundColor: '#FFF9F0',
  },
  messaginginputContainer: {
    width: '100%',
    minHeight: 100,
    height: 50,
    backgroundColor: 'white',
    paddingVertical: 30,
    paddingHorizontal: 15,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  messaginginput: {
    borderWidth: 1,
    height: 45,
    padding: 15,
    flex: 1,
    marginRight: 10,
    borderRadius: 12,
    borderColor: 'rgba(112,112,112,0.5)',
  },
  messagingbuttonContainer: {
    width: '25%',
    height: 45,
    backgroundColor: '#E24E59',
    // borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
  },

  disabledButton: {
    width: '25%',
    height: 45,
    backgroundColor: '#black',
    // borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
  },

  mmessageWrapper: {
    width: '100%',
    alignItems: 'flex-start',
    marginBottom: 15,
  },
  mmessage: {
    maxWidth: '50%',
    backgroundColor: 'white',
    padding: 15,
    borderRadius: 10,
    marginBottom: 2,
    fontSize: 30,
  },
  mvatar: {
    marginRight: 5,
  },
  cchat: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 5,
    paddingHorizontal: 15,
    backgroundColor: '#FFF9F0',
    height: 80,
    marginBottom: 5,
    paddingBottom: 5,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(112,112,112,0.5)',
  },
  cavatar: {
    marginRight: 15,
  },
  cprofilepic: {
    height: 70,
    width: 70,
    borderRadius: 30,
  },
  mprofilepic: {
    height: 50,
    width: 50,
    borderRadius: 30,
    marginRight: 6,
  },
  cusername: {
    fontSize: 18,
    marginBottom: 5,
    fontWeight: 'bold',
    color: 'black',
  },

  crightContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: 15,
    // justifyContent: 'flex-start',
    flex: 1,
  },
  crightContainer2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },

  cmessage: {
    fontSize: 14,
    opacity: 0.7,
    maxHeight:40
    // width: 200
  },
  ctime: {
    marginBottom: 5,
    opacity: 0.5,
    marginRight: 0,
    position:'absolute',
    left:175,
    width:100
  },
  tabText: {
    fontSize: 20,
  },
  tabShadow: {
    shadowColor: '#CB1F2C',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.3,
    shadowRadius: 3.5,
    elevation: 5,
  },
  subPlan: {
    fontSize: 30,
    color: '#E24E59',
    marginTop: 15,
    marginBottom: 4,
    fontWeight: 'bold',
    padding: 20,
  },
  subDetails: {
    fontSize: 15,
    color: '#E2868D',
  },
  PlanButton: {
    marginVertical: 20,
    backgroundColor: '#E24E59',
    color: '#FDDBDD',
    borderRadius: 26,
    width: 260,
    alignSelf: 'center',
  },
  PlanSubmitBtn: {
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 20,
    marginHorizontal: 10,
    backgroundColor: '#E24E59',
    width: 100,
    borderRadius: 16,
    height: 30,
  },
  hiName: {
    fontSize: 30,
    color: '#E24E59',
    fontWeight: 'bold',
    fontFamily: 'League Spartan',
  },
  welcome: {
    fontSize: 15,
    color: '#E2868D',
    fontWeight: 'bold',
  },
  BMI: {
    fontSize: 24,
    color: '#E2868D',
    marginTop: 15,
    marginLeft: 25,
    marginBottom: 4,
    fontWeight: 'bold',
    width: 180,
    height: 30,
  },
  BMIChartBtn: {
    justifyContent: 'center',
    marginTop: 20,
    marginLeft: 40,
    marginRight: 20,
    marginBottom: 4,
    backgroundColor: '#E24E59',
    width: 120,
    borderRadius: 16,
    height: 30,
  },
  BMIChartText: {
    textAlign: 'center',
    fontSize: 16,
    color: '#fff',
    fontWeight: 'bold',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalTitle: {
    marginVertical: 15,
    textAlign: 'center',
    color: '#E24E59',
    fontSize: 20,
    fontWeight: 'bold',
  },
  modalText: {
    marginBottom: 5,
    textAlign: 'center',
    color: '#E2868D',
    fontSize: 18,
  },
  setGoal: {
    textAlign: 'center',
    fontSize: 30,
    color: '#E24E59',
    marginTop: 15,
    marginBottom: 4,
    fontWeight: 'bold',
    paddingVertical: 20,
    paddingHorizontal: 5,
  },
  targetWeight: {
    fontSize: 24,
    color: '#E2868D',
    marginTop: 15,
    marginLeft: 25,
    marginBottom: 7,
    fontWeight: 'bold',
    // width: 180,
    height: 30,
  },
  weightBtn: {
    justifyContent: 'center',
    marginLeft: 20,
    marginRight: 20,
    backgroundColor: '#E24E59',
    width: 120,
    borderRadius: 16,
    height: 30,
  },
  discoverTitle: {
    textAlign: 'center',
    color: '#E24E59',
    fontSize: 24,
    fontWeight: 'bold',
    marginVertical: 20,
  },
  FilteringBtnPressed: {
    justifyContent: 'center',
    marginHorizontal: 10,
    backgroundColor: '#E24E59',
    width: 100,
    borderRadius: 16,
    height: 30,
  },
  FilteringBtn: {
    justifyContent: 'center',
    marginHorizontal: 10,
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#FDDBDD',
    width: 100,
    borderRadius: 16,
    height: 30,
  },
  FilteringBtnText: {
    textAlign: 'center',
    fontSize: 16,
    color: '#fff',
    fontWeight: 'bold',
  },
  CardInfo: {
    position: 'relative',
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingBottom: 30,
  },
  CardPT: {
    alignSelf: 'flex-end',
    marginRight: 10,
    fontSize: 16,
    color: '#E24E59',
    fontWeight: 'bold',
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: {
      width: 0,
      height: 1,
    },
    textShadowRadius: 3.5,
    elevation: 6,
  },
  DiscoverUsername: {
    color: '#E24E59',
    fontSize: 24,
    fontWeight: 'bold',
    marginHorizontal: 20,
  },
  DiscoverGym: {
    color: '#B1B1B1',
    fontSize: 16,
    fontWeight: 'bold',
    marginHorizontal: 20,
  },
  DiscoverInterest: {
    justifyContent: 'center',
    marginTop: 5,
    marginLeft: 5,
    marginBottom: 10,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#FDDBDD',
    borderRadius: 16,
  },
  DiscoverInterestText: {
    color: '#707070',
    fontSize: 15,
    fontWeight: 'bold',
    marginHorizontal: 8,
  },
  LikeIcon: {
    position: 'relative',
    bottom: 265,
    // left: 220,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    shadowColor: '#7CCD96',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.3,
    shadowRadius: 3.5,
    elevation: 6,
  },
  NopeIcon: {
    position: 'relative',
    bottom: 145,
    // left: 70,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    shadowColor: '#ED8974',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.3,
    shadowRadius: 3.5,
    elevation: 6,
  },
  SuperIcon: {
    position: 'relative',
    bottom: 205,
    left: 150,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    shadowColor: '#4FADC2',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.3,
    shadowRadius: 3.5,
    elevation: 6,
  },
  bio: {
    position: 'relative',
    paddingHorizontal: 20,
    fontSize: 16,
  },

  profileScreen: {
    backgroundColor: '#FFF9F0',
    flex: 1,
    padding: 10,
    position: 'relative',
  },
  profileHeading: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#E24E59',
    justifyContent: 'center',
  },
  profileTopContainer: {
    // backgroundColor: '#F7F7F7',
    height: 80,
    width: '100%',
    padding: 20,
    justifyContent: 'center',
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(112,112,112,0.5)',
    // elevation: 2,
  },
  profileheader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  profilelistContainer: {
    paddingHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileemptyContainer: {
    marginTop: 20,
    width: '100%',
    height: '80%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileemptyText: {fontWeight: 'bold', fontSize: 24, paddingBottom: 30},
  LogoutBtn: {
    justifyContent: 'center',
    alignContent: 'center',
    backgroundColor: '#E24E59',
    width: 120,
    borderRadius: 18,
    height: 35,
  },
  LogoutText: {
    textAlign: 'center',
    fontSize: 18,
    color: '#fff',
    fontWeight: 'bold',
  },
  matchView: {
    backgroundColor: 'rgba(255, 249, 240,0.97)',
    padding: 35,
    alignItems: 'center',
  },
  levelBtn: {
    flex: 1,
    height: height * 0.07,
    borderRadius: 16,
    borderWidth: 2,
    width: width * 0.75,
    borderColor: '#F2B3B7',
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
  },
  levelBtnPressed: {
    flex: 1,
    height: height * 0.08,
    borderRadius: 16,
    backgroundColor: '#e24e59',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0,
    width: width * 0.75,
  },
  levelBtnText: {
    textAlign: 'center',
    paddingVertical: 10,
    fontSize: 18,
    fontWeight: 'bold',
    color: '#e24e59',
  },
  levelBtnTextPressed: {
    textAlign: 'center',
    paddingVertical: 10,
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  interestBtn: {
    // flex: 1,
    height: 45,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#F2B3B7',
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: height * 0.003,
    marginVertical: height * 0.003,
  },
  interestBtnPressed: {
    // flex: 1,

    backgroundColor: '#e24e59',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  interestBtnText: {
    textAlign: 'center',
    paddingVertical: 5,
    fontSize: 18,
    fontWeight: 'bold',
    color: '#F2B3B7',
    paddingHorizontal: 20,
  },
  interestToogleBtnText: {
    textAlign: 'center',
    paddingVertical: 5,
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  pprofilepic: {
    height: 150,
    width: 150,
    borderRadius: 30,
    marginBottom:20
  },

  profiledetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 350,
    alignItems: 'center',
    marginBottom:10
    // flex: 1,
  },
  profileinput: {
    backgroundColor: 'rgba(50,50,50,0.07)',
    width: width * 0.5,
    height: height * 0.04,
    marginHorizontal: 4,
    marginVertical: 10,
    fontSize: 14,
    borderWidth: 2,
    borderRadius: 10,
    color: 'black',
    borderColor: 'rgba(50,50,50, 0.17)',
    textAlign: 'center',
    padding: 5,
  },
  profileinputbio: {
    backgroundColor: 'rgba(50,50,50,0.07)',
    maxWidth: width * 0.5,
    height: height * 0.15,
    marginHorizontal: 4,
    marginVertical: 10,
    fontSize: 14,
    flex: 1,
    flexWrap: 'wrap',
    borderWidth: 2,
    borderRadius: 12,
    color: 'black',
    borderColor: 'rgba(50,50,50, 0.17)',
    // textAlign: 'center',
    padding: 10,
  },
  matchTitle: {
    marginVertical: 20,
    textAlign: 'center',
    color: '#E24E59',
    fontSize: 35,
    fontWeight: 'bold',
  },
  backBtn: {
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 4,
    backgroundColor: '#E24E59',
    width: 200,
    borderRadius: 16,
    height: 40,
  },
  backBtnText: {
    textAlign: 'center',
    fontSize: 18,
    color: '#fff',
    fontWeight: 'bold',
  },
  matchText: {
    margin: 15,
    textAlign: 'center',
    color: '#E2868D',
    fontSize: 20,
  },
  updateBtn: {
    justifyContent: 'center',
    alignItems:'center',
    width: width * 0.86,
    height: height * 0.06,
    marginHorizontal: 4,
    marginVertical: 25,
    borderRadius: 16,
    backgroundColor: '#e24e59',
    // marginBottom:20
  },
});
